services:
  weather-api:
    build: .
    container_name: weather-api
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    volumes:
      - ".:/app"
  redis:
    image: redis:latest
    container_name: weather-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:latest
    container_name: weather-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - weather-api

volumes:
  redis-data: {} 